"use client";

import Papa from "papaparse";
import { useMemo, useState } from "react";

type Marketplace = "amazon" | "flipkart" | "meesho" | "myntra";

type CanonicalRow = {
  title?: string;
  brand?: string;
  sku?: string;
  price?: string;
  mrp?: string;
  category?: string;
  color?: string;
  size?: string;
  material?: string;
  description?: string;
  bulletPoints?: string[];
  images?: string[];
  weight?: string;
  packageDimensions?: string;
};

type SpreadsheetRow = Record<string, string>;

type GeneratedSheet = {
  marketplace: Marketplace;
  rows: SpreadsheetRow[];
  headers: string[];
};

const fieldAliases: Record<keyof CanonicalRow, RegExp[]> = {
  title: [/title/i, /name/i, /product/i],
  brand: [/brand/i, /label/i],
  sku: [/sku/i, /item\s*code/i, /seller\s*sku/i, /style\s*code/i],
  price: [/price/i, /selling/i, /offer/i],
  mrp: [/mrp/i, /list\s*price/i, /maximum/i],
  category: [/category/i, /segment/i, /type/i],
  color: [/color/i, /shade/i],
  size: [/size/i, /fit/i, /dimension/i],
  material: [/material/i, /fabric/i, /composition/i],
  description: [/description/i, /about/i, /details/i],
  bulletPoints: [/bullet/i, /feature/i, /highlights/i],
  images: [/image/i, /photo/i, /asset/i],
  weight: [/weight/i, /kg/i, /grams/i],
  packageDimensions: [/dimension/i, /package/i, /length/i],
};

const marketplaceHeaders: Record<Marketplace, string[]> = {
  amazon: [
    "Feed Product Type",
    "Item SKU",
    "Product ID Type",
    "Product ID",
    "Item Name",
    "Brand Name",
    "Recommended Browse Node",
    "Standard Price",
    "Quantity",
    "Main Image URL",
    "Other Image URL1",
    "Other Image URL2",
    "Parentage",
    "Variation Theme",
    "Color",
    "Size",
    "Material",
    "Bullet Point1",
    "Bullet Point2",
    "Bullet Point3",
    "Generic Keywords",
  ],
  flipkart: [
    "Seller SKU",
    "Product Name",
    "HSN",
    "Selling Price",
    "MRP",
    "Procurement SLA",
    "Product Description",
    "Highlights",
    "Main Image",
    "Image 2",
    "Image 3",
    "Category",
    "Color",
    "Size",
    "Occasion",
    "Material",
    "Package Weight",
    "Country of Origin",
  ],
  meesho: [
    "Unique ID",
    "Product Title",
    "Category",
    "Sub Category",
    "Price",
    "MRP",
    "Fabric / Material",
    "Color",
    "Size",
    "Description",
    "Images",
    "Pack Of",
    "Care Instructions",
  ],
  myntra: [
    "Style Code",
    "Item Name",
    "Brand",
    "Story",
    "Product Group",
    "Inventory Qty",
    "MRP",
    "Selling Price",
    "USP 1",
    "USP 2",
    "USP 3",
    "Primary Color",
    "Secondary Color",
    "Size",
    "Fabric",
    "Pattern",
    "Ideal For",
    "Product Description",
    "Images",
  ],
};

const defaultValues: Record<Marketplace, Partial<SpreadsheetRow>> = {
  amazon: {
    Parentage: "child",
    VariationTheme: "SizeColor",
    Quantity: "10",
    "Product ID Type": "EAN",
    "Feed Product Type": "apparel",
  },
  flipkart: {
    "Procurement SLA": "2",
    "Country of Origin": "India",
  },
  meesho: {
    "Pack Of": "1",
    "Care Instructions": "Follow label instructions",
  },
  myntra: {
    Story: "Automated listing generated by Jarvis",
    "Product Group": "Apparel",
    "Inventory Qty": "10",
    "Ideal For": "Unisex",
  },
};

const marketplaceName: Record<Marketplace, string> = {
  amazon: "Amazon Seller Central",
  flipkart: "Flipkart Seller Hub",
  meesho: "Meesho Supplier Panel",
  myntra: "Myntra Partner Portal",
};

const MAX_ROWS_PREVIEW = 10;

function normaliseRow(row: SpreadsheetRow): CanonicalRow {
  const canonical: CanonicalRow = {};
  const keys = Object.keys(row);

  keys.forEach((key) => {
    const value = row[key]?.toString().trim();
    if (!value) return;

    Object.entries(fieldAliases).forEach(([canonicalField, patterns]) => {
      patterns.forEach((pattern) => {
        if (pattern.test(key)) {
          if (canonicalField === "bulletPoints" || canonicalField === "images") {
            const existing = canonical[canonicalField]?.slice() ?? [];
            const fragments = value.split(/[,|•\n]/).map((fragment) => fragment.trim());
            canonical[canonicalField] = Array.from(
              new Set([...existing, ...fragments.filter((fragment) => fragment.length > 0)])
            );
          } else {
            (canonical as Record<string, string>)[canonicalField] = value;
          }
        }
      });
    });
  });

  if (!canonical.bulletPoints && canonical.description) {
    canonical.bulletPoints = canonical.description
      .split(/[.|\n]/)
      .map((point) => point.trim())
      .filter((point) => point.length >= 10)
      .slice(0, 5);
  }

  return canonical;
}

function buildMarketplaceRow(marketplace: Marketplace, canonical: CanonicalRow): SpreadsheetRow {
  const row: SpreadsheetRow = {};
  const headers = marketplaceHeaders[marketplace];

  headers.forEach((header) => {
    switch (marketplace) {
      case "amazon": {
        if (header === "Item SKU") row[header] = canonical.sku ?? "";
        else if (header === "Item Name") row[header] = canonical.title ?? "";
        else if (header === "Brand Name") row[header] = canonical.brand ?? "";
        else if (header === "Standard Price") row[header] = canonical.price ?? canonical.mrp ?? "";
        else if (header.startsWith("Bullet Point")) {
          const index = parseInt(header.replace(/\D/g, ""), 10) - 1;
          row[header] = canonical.bulletPoints?.[index] ?? "";
        } else if (header === "Generic Keywords") {
          const keywords = [
            canonical.category,
            canonical.color,
            canonical.material,
            ...(canonical.bulletPoints ?? []),
          ]
            .filter(Boolean)
            .join(", ");
          row[header] = keywords;
        } else if (header === "Color") row[header] = canonical.color ?? "";
        else if (header === "Size") row[header] = canonical.size ?? "";
        else if (header === "Material") row[header] = canonical.material ?? "";
        else if (header === "Main Image URL") row[header] = canonical.images?.[0] ?? "";
        else if (header === "Other Image URL1") row[header] = canonical.images?.[1] ?? "";
        else if (header === "Other Image URL2") row[header] = canonical.images?.[2] ?? "";
        else row[header] = "";
        break;
      }
      case "flipkart": {
        if (header === "Seller SKU") row[header] = canonical.sku ?? "";
        else if (header === "Product Name") row[header] = canonical.title ?? "";
        else if (header === "Selling Price") row[header] = canonical.price ?? "";
        else if (header === "MRP") row[header] = canonical.mrp ?? canonical.price ?? "";
        else if (header === "Product Description") row[header] = canonical.description ?? "";
        else if (header === "Highlights") row[header] = (canonical.bulletPoints ?? []).join(" | ");
        else if (header === "Main Image") row[header] = canonical.images?.[0] ?? "";
        else if (header === "Image 2") row[header] = canonical.images?.[1] ?? "";
        else if (header === "Image 3") row[header] = canonical.images?.[2] ?? "";
        else if (header === "Category") row[header] = canonical.category ?? "";
        else if (header === "Color") row[header] = canonical.color ?? "";
        else if (header === "Size") row[header] = canonical.size ?? "";
        else if (header === "Occasion")
          row[header] = canonical.category?.includes("festive") ? "Festive" : "Casual";
        else if (header === "Material") row[header] = canonical.material ?? "";
        else if (header === "Package Weight") row[header] = canonical.weight ?? "0.4";
        else row[header] = "";
        break;
      }
      case "meesho": {
        if (header === "Unique ID") row[header] = canonical.sku ?? "";
        else if (header === "Product Title") row[header] = canonical.title ?? "";
        else if (header === "Category") row[header] = canonical.category ?? "";
        else if (header === "Sub Category")
          row[header] = canonical.category?.split(">").pop()?.trim() ?? "";
        else if (header === "Price") row[header] = canonical.price ?? "";
        else if (header === "MRP") row[header] = canonical.mrp ?? canonical.price ?? "";
        else if (header === "Fabric / Material") row[header] = canonical.material ?? "";
        else if (header === "Color") row[header] = canonical.color ?? "";
        else if (header === "Size") row[header] = canonical.size ?? "";
        else if (header === "Description") row[header] = canonical.description ?? "";
        else if (header === "Images") row[header] = (canonical.images ?? []).join(", ");
        else row[header] = "";
        break;
      }
      case "myntra": {
        if (header === "Style Code") row[header] = canonical.sku ?? "";
        else if (header === "Item Name") row[header] = canonical.title ?? "";
        else if (header === "Brand") row[header] = canonical.brand ?? "";
        else if (header === "USP 1") row[header] = canonical.bulletPoints?.[0] ?? "";
        else if (header === "USP 2") row[header] = canonical.bulletPoints?.[1] ?? "";
        else if (header === "USP 3") row[header] = canonical.bulletPoints?.[2] ?? "";
        else if (header === "Selling Price") row[header] = canonical.price ?? "";
        else if (header === "MRP") row[header] = canonical.mrp ?? canonical.price ?? "";
        else if (header === "Primary Color") row[header] = canonical.color ?? "";
        else if (header === "Secondary Color")
          row[header] = canonical.color?.includes("/")
            ? canonical.color.split("/")[1]
            : canonical.color ?? "";
        else if (header === "Size") row[header] = canonical.size ?? "";
        else if (header === "Fabric") row[header] = canonical.material ?? "";
        else if (header === "Pattern") {
          const pattern =
            canonical.description?.match(/(striped|solid|checked|printed|embroidered)/i)?.[0] ??
            "Solid";
          row[header] = pattern;
        } else if (header === "Product Description") row[header] = canonical.description ?? "";
        else if (header === "Images") row[header] = (canonical.images ?? []).join(", ");
        else row[header] = "";
        break;
      }
      default:
        row[header] = "";
    }
  });

  const enrichedRow = { ...defaultValues[marketplace], ...row };

  return headers.reduce<SpreadsheetRow>((accumulator, header) => {
    const value = enrichedRow[header];
    accumulator[header] = typeof value === "string" ? value : "";
    return accumulator;
  }, {} as SpreadsheetRow);
}

function convertToSheet(
  rawRows: SpreadsheetRow[],
  marketplace: Marketplace
): GeneratedSheet {
  const headers = marketplaceHeaders[marketplace];
  const rows = rawRows
    .map(normaliseRow)
    .map((canonical) => buildMarketplaceRow(marketplace, canonical));

  return { headers, rows, marketplace };
}

function downloadCsv(sheet: GeneratedSheet) {
  const csv = Papa.unparse({
    fields: sheet.headers,
    data: sheet.rows.map((row) => sheet.headers.map((header) => row[header] ?? "")),
  });

  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", `${sheet.marketplace}-catalog.csv`);
  link.click();
  URL.revokeObjectURL(url);
}

export function CatalogAssistant() {
  const [rawRows, setRawRows] = useState<SpreadsheetRow[]>([]);
  const [sheets, setSheets] = useState<GeneratedSheet[]>([]);
  const [isParsing, setIsParsing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const previewRows = useMemo(() => rawRows.slice(0, MAX_ROWS_PREVIEW), [rawRows]);

  const handleFile = async (file?: File) => {
    if (!file) return;
    setIsParsing(true);
    setError(null);

    Papa.parse<SpreadsheetRow>(file, {
      header: true,
      skipEmptyLines: true,
      complete: (result) => {
        const parsedRows = result.data.filter((row) =>
          Object.values(row).some((value) => (value ?? "").toString().trim().length > 0)
        );
        setRawRows(parsedRows);
        setSheets([]);
        setIsParsing(false);
      },
      error: (parseError) => {
        setError(parseError.message);
        setIsParsing(false);
      },
    });
  };

  const generate = (marketplace: Marketplace) => {
    if (rawRows.length === 0) {
      setError("Upload your raw catalog sheet first.");
      return;
    }
    const sheet = convertToSheet(rawRows, marketplace);
    setSheets((prev) => {
      const withoutMarketplace = prev.filter((item) => item.marketplace !== marketplace);
      return [...withoutMarketplace, sheet];
    });
    setError(null);
  };

  return (
    <section className="rounded-3xl border border-white/15 bg-white/95 p-6 shadow-xl backdrop-blur-sm dark:border-white/10 dark:bg-zinc-950/80">
      <header className="flex flex-col gap-2 pb-4">
        <h2 className="text-xl font-semibold text-zinc-900 dark:text-white">
          Catalog Automation Lab
        </h2>
        <p className="text-sm text-zinc-600 dark:text-zinc-300">
          Drop in your master catalog spreadsheet. Jarvis maps attributes and produces ready-to-upload
          sheets for Amazon, Flipkart, Meesho, and Myntra within seconds.
        </p>
      </header>

      <div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]">
        <div className="space-y-4">
          <label className="flex flex-col items-center justify-center gap-3 rounded-2xl border border-dashed border-emerald-400/60 bg-emerald-50/40 p-6 text-sm font-medium text-emerald-900 transition hover:border-emerald-500 hover:bg-emerald-100/60 dark:border-emerald-400/30 dark:bg-emerald-500/10 dark:text-emerald-100">
            <input
              type="file"
              accept=".csv,.xls,.xlsx"
              className="hidden"
              onChange={(event) => handleFile(event.target.files?.[0])}
            />
            {isParsing ? (
              <span className="animate-pulse">Parsing sheet…</span>
            ) : rawRows.length ? (
              <>
                <span className="text-lg font-semibold">
                  {rawRows.length} products loaded
                </span>
                <span className="text-xs text-emerald-800/70 dark:text-emerald-200/80">
                  Replace file to refresh
                </span>
              </>
            ) : (
              <>
                <span className="text-lg font-semibold">Upload master catalog</span>
                <span className="text-xs text-emerald-800/70 dark:text-emerald-200/80">
                  CSV or Excel exported as CSV with headers
                </span>
              </>
            )}
          </label>

          {previewRows.length > 0 && (
            <div className="rounded-2xl border border-white/40 bg-white/80 p-4 text-sm shadow-inner dark:border-white/10 dark:bg-zinc-900/50 dark:text-zinc-100">
              <h3 className="text-sm font-semibold text-emerald-600 dark:text-emerald-300">
                Raw Data Preview
              </h3>
              <div className="mt-3 max-h-56 overflow-auto">
                <table className="min-w-full text-left">
                  <thead className="sticky top-0 bg-white/80 text-xs uppercase tracking-wide text-zinc-500 dark:bg-zinc-900/90 dark:text-zinc-400">
                    <tr>
                      {Object.keys(previewRows[0]).map((header) => (
                        <th key={header} className="px-2 py-1">
                          {header}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-zinc-200/40 dark:divide-white/10">
                    {previewRows.map((row, index) => (
                      <tr key={index}>
                        {Object.values(row).map((value, valueIndex) => (
                          <td key={valueIndex} className="px-2 py-2 align-top">
                            {value}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>

        <div className="flex flex-col gap-4">
          <div className="rounded-2xl border border-zinc-200 bg-white/90 p-4 shadow-inner dark:border-white/10 dark:bg-zinc-900/70">
            <h3 className="text-sm font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-300">
              Generate Channel Sheets
            </h3>
            <div className="mt-3 grid gap-3">
              {(Object.keys(marketplaceHeaders) as Marketplace[]).map((marketplace) => (
                <button
                  key={marketplace}
                  type="button"
                  onClick={() => generate(marketplace)}
                  className="flex items-center justify-between rounded-xl border border-zinc-200 bg-white px-3 py-3 text-left text-sm font-medium text-zinc-800 shadow-sm transition hover:border-emerald-400 hover:ring-2 hover:ring-emerald-200 dark:border-white/10 dark:bg-zinc-900 dark:text-zinc-100 dark:hover:border-emerald-400/50 dark:hover:ring-emerald-500/20"
                >
                  <span>{marketplaceName[marketplace]}</span>
                  <span className="text-xs uppercase tracking-wide text-emerald-500">
                    Generate
                  </span>
                </button>
              ))}
            </div>
          </div>

          {sheets.length > 0 && (
            <div className="space-y-4">
              {sheets.map((sheet) => (
                <article
                  key={sheet.marketplace}
                  className="rounded-2xl border border-emerald-200/70 bg-emerald-50 p-4 shadow-lg shadow-emerald-200/40 dark:border-emerald-500/30 dark:bg-emerald-500/10"
                >
                  <header className="flex items-center justify-between gap-3">
                    <div>
                      <h4 className="text-base font-semibold text-emerald-900 dark:text-emerald-100">
                        {marketplaceName[sheet.marketplace]}
                      </h4>
                      <p className="text-xs text-emerald-800/70 dark:text-emerald-200/80">
                        {sheet.rows.length} rows ready · {sheet.headers.length} attributes mapped
                      </p>
                    </div>
                    <button
                      type="button"
                      onClick={() => downloadCsv(sheet)}
                      className="rounded-full border border-emerald-500 bg-emerald-500 px-3 py-1 text-xs font-semibold text-white transition hover:bg-emerald-400"
                    >
                      Download CSV
                    </button>
                  </header>

                  <div className="mt-3 max-h-40 overflow-auto rounded-xl bg-white/90 p-3 text-xs shadow-inner dark:bg-zinc-900/80 dark:text-zinc-100">
                    <table className="min-w-full text-left">
                      <thead className="sticky top-0 bg-emerald-100 text-[10px] uppercase tracking-wide text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-100">
                        <tr>
                          {sheet.headers.map((header) => (
                            <th key={header} className="px-2 py-1">
                              {header}
                            </th>
                          ))}
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-emerald-100 dark:divide-emerald-500/20">
                        {sheet.rows.slice(0, MAX_ROWS_PREVIEW).map((row, index) => (
                          <tr key={index}>
                            {sheet.headers.map((header) => (
                              <td key={header} className="px-2 py-1 align-top">
                                {row[header]}
                              </td>
                            ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                    {sheet.rows.length > MAX_ROWS_PREVIEW && (
                      <p className="mt-2 text-[10px] font-medium text-emerald-600 dark:text-emerald-200">
                        Showing {MAX_ROWS_PREVIEW} of {sheet.rows.length} rows.
                      </p>
                    )}
                  </div>
                </article>
              ))}
            </div>
          )}

          {error && (
            <div className="rounded-2xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700 dark:border-rose-500/30 dark:bg-rose-500/10 dark:text-rose-100">
              {error}
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
